// Datos mock para desarrollo

// Usuarios de prueba
export const mockUsuarios = [
    {
        id: 'admin-001',
        nombre: 'Administrador',
        telefono: '3814011673',
        email: 'admin@superaguilares.com',
        rol: 'admin' as const,
    },
    {
        id: 'cliente-001',
        nombre: 'Cliente Demo',
        telefono: '3863502004',
        email: 'cliente@demo.com',
        rol: 'cliente' as const,
    },
]

export const mockCategorias = [
    { id: '1', nombre: 'Alimentos', activo: true },
    { id: '2', nombre: 'Lácteos', activo: true },
    { id: '3', nombre: 'Carnes', activo: true },
    { id: '4', nombre: 'Bebidas', activo: true },
    { id: '5', nombre: 'Panadería', activo: true },
    { id: '6', nombre: 'Limpieza', activo: true },
]

export const mockProductos = [
    {
        id: '1',
        nombre: 'Arroz Gallo Oro 1kg',
        descripcion: 'Arroz largo fino de alta calidad. Ideal para acompañar cualquier plato.',
        precio: 1500,
        imagen_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
        categoria_id: '1',
        activo: true,
        stock: 50,
        stock_minimo: 10,
    },
    {
        id: '2',
        nombre: 'Fideos Matarazzo 500g',
        descripcion: 'Fideos tiras finitas de sémola. Cocción al dente perfecta.',
        precio: 1200,
        imagen_url: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500',
        categoria_id: '1',
        activo: true,
        stock: 80,
        stock_minimo: 15,
    },
    {
        id: '3',
        nombre: 'Yerba Mate Playadito 500g',
        descripcion: 'Yerba mate con palo de selección especial. Sabor intenso y duradero.',
        precio: 3500,
        precio_original: 4200,
        imagen_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500',
        categoria_id: '1',
        activo: true,
        stock: 60,
        stock_minimo: 20,
        descuento: '-17%',
    },
    {
        id: '4',
        nombre: 'Leche La Serenísima 1L',
        descripcion: 'Leche entera pasteurizada. Alta en calcio y proteínas.',
        precio: 1000,
        imagen_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500',
        categoria_id: '2',
        activo: true,
        stock: 100,
        stock_minimo: 25,
    },
    {
        id: '5',
        nombre: 'Carne Vacuna 1kg',
        descripcion: 'Corte premium de carne vacuna. Ideal para asado o milanesas.',
        precio: 12000,
        imagen_url: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
        categoria_id: '3',
        activo: true,
        stock: 30,
        stock_minimo: 5,
    },
    {
        id: '6',
        nombre: 'Coca-Cola 2.25L',
        descripcion: 'Bebida gaseosa clásica. Refrescante y deliciosa.',
        precio: 2000,
        imagen_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500',
        categoria_id: '4',
        activo: true,
        stock: 90,
        stock_minimo: 20,
    },
    {
        id: '7',
        nombre: 'Pan Casero 1kg',
        descripcion: 'Pan de masa madre horneado diariamente. Crocante por fuera, suave por dentro.',
        precio: 1500,
        imagen_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
        categoria_id: '5',
        activo: true,
        stock: 40,
        stock_minimo: 10,
    },
    {
        id: '8',
        nombre: 'Aceite Natura 1L',
        descripcion: 'Aceite de girasol refinado. Ideal para cocinar y freír.',
        precio: 2500,
        imagen_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
        categoria_id: '1',
        activo: true,
        stock: 70,
        stock_minimo: 15,
    },
    {
        id: '9',
        nombre: 'Azúcar Ledesma 1kg',
        descripcion: 'Azúcar blanca refinada. Perfecta para endulzar tus bebidas.',
        precio: 1800,
        imagen_url: 'https://images.unsplash.com/photo-1550411294-875e0b9a1c36?w=500',
        categoria_id: '1',
        activo: true,
        stock: 85,
        stock_minimo: 20,
    },
    {
        id: '10',
        nombre: 'Detergente Magistral 1L',
        descripcion: 'Detergente líquido para ropa. Elimina manchas difíciles.',
        precio: 2200,
        imagen_url: 'https://images.unsplash.com/photo-1628689469838-524a4a973b8e?w=500',
        categoria_id: '6',
        activo: true,
        stock: 55,
        stock_minimo: 10,
    },
]

export const mockPedidos = [
    {
        id: '1',
        numero: 'PED-2026-001',
        estado: 'recibido',
        fecha_creacion: '2026-01-15T10:30:00',
        total: 18500,
        subtotal: 18500,
        recargo: 0,
        cuotas: 0,
        metodo_pago: 'efectivo',
        pago_validado: true,
        usuarios: {
            nombre: 'Juan Pérez',
            email: 'juan.perez@email.com',
            telefono: '3814011673',
        },
        datos_entrega: {
            direccion: 'Av. San Martín 1234, Piso 4, Depto A',
            ciudad: 'Tucumán',
            codigo_postal: '4000',
        },
        pedido_items: [
            {
                id: '1',
                productos: {
                    nombre: 'Carne Vacuna 1kg',
                    imagen_url: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500',
                },
                cantidad: 1,
                precio_unitario: 12000,
                subtotal: 12000,
            },
            {
                id: '2',
                productos: {
                    nombre: 'Yerba Mate Playadito 500g',
                    imagen_url: 'https://images.unsplash.com/photo-1615447550545-8f8e6b8e3b4e?w=500',
                },
                cantidad: 1,
                precio_unitario: 3500,
                subtotal: 3500,
            },
            {
                id: '3',
                productos: {
                    nombre: 'Arroz Gallo Oro 1kg',
                    imagen_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
                },
                cantidad: 2,
                precio_unitario: 1500,
                subtotal: 3000,
            },
        ],
    },
    {
        id: '2',
        numero: 'PED-2026-002',
        estado: 'preparacion',
        fecha_creacion: '2026-01-15T14:20:00',
        total: 7000,
        subtotal: 7000,
        recargo: 0,
        cuotas: 0,
        metodo_pago: 'tarjeta',
        pago_validado: true,
        usuarios: {
            nombre: 'María González',
            email: 'maria.gonzalez@email.com',
            telefono: '3815551234',
        },
        datos_entrega: {
            direccion: 'Calle Belgrano 567',
            ciudad: 'San Miguel de Tucumán',
            codigo_postal: '4000',
        },
        pedido_items: [
            {
                id: '4',
                productos: {
                    nombre: 'Leche La Serenísima 1L',
                    imagen_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500',
                },
                cantidad: 3,
                precio_unitario: 1000,
                subtotal: 3000,
            },
            {
                id: '5',
                productos: {
                    nombre: 'Pan Casero 1kg',
                    imagen_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500',
                },
                cantidad: 2,
                precio_unitario: 1500,
                subtotal: 3000,
            },
            {
                id: '6',
                productos: {
                    nombre: 'Detergente Magistral 1L',
                    imagen_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500',
                },
                cantidad: 1,
                precio_unitario: 2200,
                subtotal: 2200,
            },
        ],
    },
    {
        id: '3',
        numero: 'PED-2026-003',
        estado: 'en_camino',
        fecha_creacion: '2026-01-14T09:15:00',
        total: 12500,
        subtotal: 12500,
        recargo: 0,
        cuotas: 0,
        metodo_pago: 'transferencia',
        pago_validado: true,
        usuarios: {
            nombre: 'Carlos López',
            email: 'carlos.lopez@email.com',
            telefono: '3816667890',
        },
        datos_entrega: {
            direccion: 'Av. Independencia 890',
            ciudad: 'Yerba Buena',
            codigo_postal: '4107',
        },
        pedido_items: [
            {
                id: '7',
                productos: {
                    nombre: 'Coca-Cola 2.25L',
                    imagen_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500',
                },
                cantidad: 2,
                precio_unitario: 2000,
                subtotal: 4000,
            },
            {
                id: '8',
                productos: {
                    nombre: 'Aceite Natura 1L',
                    imagen_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
                },
                cantidad: 2,
                precio_unitario: 2500,
                subtotal: 5000,
            },
            {
                id: '9',
                productos: {
                    nombre: 'Fideos Matarazzo 500g',
                    imagen_url: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500',
                },
                cantidad: 3,
                precio_unitario: 1200,
                subtotal: 3600,
            },
        ],
    },
]

export const mockPagos = [
    {
        id: '1',
        pedido_id: '1',
        numero: 'PED-2026-001',
        monto: 18500,
        metodo: 'efectivo',
        fecha: '2026-01-15T10:30:00',
        fecha_creacion: '2026-01-15T10:30:00',
        estado: 'aprobado',
        total: 18500,
        comprobante_url: 'https://example.com/comprobante1.jpg',
        usuarios: {
            nombre: 'Juan Pérez',
            email: 'juan.perez@email.com',
            telefono: '3814011673',
        },
    },
    {
        id: '2',
        pedido_id: '2',
        numero: 'PED-2026-002',
        monto: 7000,
        metodo: 'tarjeta',
        fecha: '2026-01-15T14:20:00',
        fecha_creacion: '2026-01-15T14:20:00',
        estado: 'pendiente',
        total: 7000,
        comprobante_url: 'https://example.com/comprobante2.jpg',
        usuarios: {
            nombre: 'María González',
            email: 'maria.gonzalez@email.com',
            telefono: '3815551234',
        },
    },
]

export const mockReportes = {
    daily: [
        { date: '2026-01-10', total: 125000, orders: 3 },
        { date: '2026-01-11', total: 89000, orders: 2 },
        { date: '2026-01-12', total: 210000, orders: 5 },
        { date: '2026-01-13', total: 165000, orders: 4 },
        { date: '2026-01-14', total: 98000, orders: 2 },
        { date: '2026-01-15', total: 184800, orders: 3 },
    ],
    categories: [
        { name: 'Alimentos', count: 45 },
        { name: 'Lácteos', count: 30 },
        { name: 'Carnes', count: 25 },
        { name: 'Bebidas', count: 40 },
        { name: 'Panadería', count: 20 },
        { name: 'Limpieza', count: 15 },
    ],
}
